[[redirects]]
  from = "/chatroom"
  to = "https://tredagle.herokuapp.com/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"