name: CI/CD configure
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Run ESLint
        # You may pin to the exact commit or the version.
        # uses: stefanoeb/eslint-action@0b532bcd98dbed80a59071fa8986fcf1b1715be4
        uses: stefanoeb/eslint-action@1.0.2
        with:
          # Blob of files to lint
          files: .
      - run: echo "This job's status is ${{ job.status }}."
